name: TON LOC Reporter

description: "Reports Lines of Code (LOC) statistics and adds comments to Pull Requests."

author: "alan890104"

inputs:
  directory:
    description: "The directory to scan for code files."
    required: true
    default: "."
  language:
    description: "The programming language to analyze (e.g., .fc, .tolk)."
    required: true
  ignore-folders:
    description: "Comma-separated list of folders to ignore, relative to the directory."
    required: false
    default: ""
  ignore-files:
    description: "Comma-separated list of files to ignore, relative to the directory."
    required: false
    default: ""

runs:
  using: "docker"
  image: "./Dockerfile"
  args:
    - --directory
    - ${{ inputs.directory }}
    - --language
    - ${{ inputs.language }}
    - --ignore-folders
    - ${{ inputs.ignore-folders }}
    - --ignore-files
    - ${{ inputs.ignore-files }}

branding:
  icon: "code"
  color: "blue"
